<?php

/**
 * Localizations for the Kolab libkolab plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libkolab/
 */

$labels = [];

// history dialog
$labels['showhistory'] = 'Show History';
$labels['compare'] = 'Compare';
$labels['objectchangelog'] = 'History';
$labels['objectdiff'] = 'Changes from $rev1 to $rev2';
$labels['revision'] = 'Revision';
$labels['user'] = 'User';
$labels['operation'] = 'Action';
$labels['actionreceive'] = 'Received';
$labels['actionappend'] = 'Saved';
$labels['actionmove'] = 'Moved';
$labels['actiondelete'] = 'Deleted';
$labels['actionread'] = 'Marked as Read';
$labels['actionflagset'] = 'Flag set';
$labels['actionflagclear'] = 'Flag removed';
$labels['showrevision'] = 'Show this version';
$labels['restore'] = 'Restore this version';
$labels['objectchangelognotavailable'] = 'History is not available for this object.';
$labels['tabsharing'] = 'Sharing';
$labels['aclnorights'] = 'You do not have administrator rights for this folder.';

// Folder ACL (Sharing tab)
$labels['add'] = 'Add';
$labels['all'] = 'Anyone';
$labels['authenticated'] = 'Authenticated users';
$labels['identifier'] = 'Identifier';
$labels['newuser'] = 'Add entry';
$labels['actions'] = 'Access right actions...';
$labels['username'] = 'User:';
$labels['myrights'] = 'Access Rights';
$labels['editperms'] = 'Edit permissions';
$labels['aclall'] = 'All';
$labels['aclread'] = 'Read';
$labels['aclwrite'] = 'Write';
$labels['aclread-free-busy'] = 'Free-Busy';
$labels['acllongall'] = 'All (administration)';

$labels['ariasummaryacltable'] = 'List of access rights';
$labels['arialabelaclactions'] = 'List actions';
$labels['arialabelaclform'] = 'Access rights form';

$messages['deleting'] = 'Deleting access rights...';
$messages['saving'] = 'Saving access rights...';
$messages['updatesuccess'] = 'Successfully changed access rights';
$messages['deletesuccess'] = 'Successfully deleted access rights';
$messages['createsuccess'] = 'Successfully added access rights';
$messages['updateerror'] = 'Unable to update access rights';
$messages['deleteerror'] = 'Unable to delete access rights';
$messages['createerror'] = 'Unable to add access rights';
$messages['deleteconfirm'] = 'Are you sure, you want to remove access rights of selected user(s)?';
$messages['norights'] = 'No rights has been specified!';
$messages['nouser'] = 'No username has been specified!';
